const express = require("express");
const router = express.Router();
const userController = require("../Controllers/userController");
router.post("/login", userController.login);
router.post("/register", userController.register);
router.get("/getallusers", userController.getAllUsers);
router.get("/profile/:id", userController.getDetails);
router.put("/profile/:id", userController.updateDetails);
router.put("/submitcertificate", userController.updateDetailsAfterSubmit);
router.put("/begincertificate", userController.updateDetailsAfterBegin);
module.exports = router;
